Repository RockChinQ/LangBot, pull requests merged in 2023-04, with the labels that each got.

#368 [Chore] 统一docstring格式
  pkg/openai/__init__.py
  pkg/openai/keymgr.py
  pkg/plugin/host.py
  pkg/plugin/switch.py
  pkg/utils/threadctl.py
Labels: documentation, codestyle

#381 [Chore] 删除冗余的兼容性检查判断
  main.py
  pkg/audit/gatherer.py
  pkg/openai/manager.py
  pkg/openai/session.py
  pkg/qqbot/blob.py
  pkg/qqbot/cmds/system/help.py
  pkg/qqbot/filter.py
  pkg/qqbot/ignore.py
  pkg/qqbot/manager.py
  pkg/qqbot/message.py
  pkg/qqbot/process.py
  pkg/qqbot/ratelimit.py
  pkg/utils/text2img.py
  tests/gpt3_test.py
Labels: codestyle

#356 [Feat] 支持自定义提示消息
  tips-custom-template.py
Labels: enhancement, 会话管理

#418 [Refactor] 新增抽象层以解耦消息来源（MessageSource）组件
  config-template.py
  main.py
  override-all.json
  pkg/openai/modelmgr.py
  pkg/plugin/host.py
  pkg/qqbot/adapter.py
  pkg/qqbot/manager.py
  pkg/qqbot/process.py
  pkg/qqbot/sources/__init__.py
  pkg/qqbot/sources/yirimirai.py
Labels: 消息处理, codestyle

#427 [Feat] 通过nakuru-project框架连接go-cqhttp
  .gitignore
  README.md
  README_en.md
  config-template.py
  main.py
  override-all.json
  pkg/qqbot/adapter.py
  pkg/qqbot/manager.py
  pkg/qqbot/process.py
  pkg/qqbot/sources/nakuru.py
  pkg/qqbot/sources/yirimirai.py
  pkg/utils/log.py
  requirements.txt
  res/announcement.json
  res/wiki/go-cqhttp配置.md
Labels: 消息处理

#433 [Feat] 细化到单个群的响应规则
  config-template.py
  override-all.json
  pkg/qqbot/manager.py
Labels: 消息处理
