Repository RockChinQ/LangBot, pull requests merged in 2023-03, with the labels that each got.

#194 重构了模型抽象，用来更好的支持gpt-3.5-turbo
  README.md
  config-template.py
  pkg/database/manager.py
  pkg/openai/manager.py
  pkg/openai/modelmgr.py
  pkg/openai/session.py
  pkg/qqbot/command.py
  requirements.txt
  tests/compatibility_tests/models_and_interfaces.py
Labels: enhancement

#200 添加proxy代理功能
  config-template.py
  pkg/openai/manager.py
  pkg/openai/modelmgr.py
Labels: enhancement, openai

#212 增加百度云内容审核
  README.md
  config-template.py
  pkg/qqbot/filter.py
Labels: enhancement, dev

#215 [Feature] 使用语义化版本进行更新
  .gitignore
  main.py
  pkg/utils/updater.py
  requirements.txt
Labels: enhancement

#219 优化异常处理
  pkg/openai/modelmgr.py
Labels: enhancement, dev

#225 [Fix] 修复插件开关问题
  README.md
  pkg/utils/reloader.py
Labels: bug

#228 启动时，更新openai和pillow库超时问题
  main.py
Labels: enhancement, dependencies

#222 使用线程池控制线程数量，防止高并发崩溃
  config-template.py
  main.py
  pkg/qqbot/manager.py
Labels: enhancement

#230 添加配置文件完整性校验
  main.py
Labels: enhancement

#233 [Feat] 支持设置不响应群内at消息及随机响应
  config-template.py
  pkg/qqbot/manager.py
Labels: enhancement

#236 [Fix] !reload 重新加载以后首次对话报错
  main.py
Labels: bug?

#263 [Feat] 支持删除会话的指定或全部历史记录 (#239)
  config-template.py
  main.py
  pkg/database/manager.py
  pkg/openai/session.py
  pkg/qqbot/command.py
Labels: enhancement

#262 [Feat] 情景预设（人格）完善
  .gitignore
  config-template.py
  main.py
  pkg/database/manager.py
  pkg/openai/dprompt.py
  pkg/openai/keymgr.py
  pkg/openai/session.py
  pkg/qqbot/command.py
  scenario/default-template.json
Labels: enhancement, 情景预设

#271 feat: 支持json格式的配置文件 (#265)
  .gitignore
  main.py
Labels: enhancement

#280 [Feat] 添加公告输出功能
  main.py
  pkg/utils/announcement.py
Labels: enhancement

#282 修复usage命令的代理问题
  pkg/qqbot/command.py
  pkg/utils/credit.py
Labels: enhancement

#300 [Perf] Tokens相关处理逻辑优化
  config-template.py
  pkg/database/manager.py
  pkg/openai/manager.py
  pkg/openai/session.py
  tests/token_test/__init__.py
  tests/token_test/token_count.py
Labels: enhancement, 情景预设, 会话管理

#304 [Perf] 百度云审核的异常处理
  pkg/qqbot/blob.py
Labels: enhancement

#323 [Feat] 基于线程池的多线程控制方案基础架构
  config-template.py
  main.py
  pkg/qqbot/manager.py
  pkg/utils/__init__.py
  pkg/utils/context.py
  pkg/utils/reloader.py
  pkg/utils/threadctl.py
Labels: enhancement

#327 Dockerfile部署
  Dockerfile
  README.md
  docker_deploy.md
Labels: get-started

#325 [Feat] 完善情景预设相关内容
  config-template.py
  main.py
  override-all.json
  pkg/openai/dprompt.py
  pkg/openai/session.py
  pkg/qqbot/cmds/session.py
Labels: enhancement, 情景预设, 指令

#332 [Feat] 支持反向代理
  config-template.py
  main.py
Labels: enhancement, OpenAI
