Repository RockChinQ/LangBot, pull requests merged in 2023-09, with the labels that each got.

#351 Create build_docker_image.yml
  .github/workflows/build_docker_image.yml
Labels: documentation, enhancement, 待测试

#565 [CI] Docker 部署脚本同步
  .github/workflows/build_docker_image.yml
Labels: 部署, 待测试

#551 加入one-api项目支持的国内大模型
  README.md
  pkg/openai/modelmgr.py
Labels: LLM, 待测试

#577 [Doc] 修复wiki中的死链
  README.md
  res/wiki/1-功能使用.md
  res/wiki/2-功能常见问题.md
  res/wiki/7-插件开发.md
Labels: 文档

#578 [Fix] 阻塞地发送审计报告数据
  pkg/audit/gatherer.py
Labels: bug?
